project = "absolute-hub-460713-v0"
region  = "us-central1"
zone    = "us-central1-c"
zones   = ["us-central1-b", "us-central1-c"]
vm_name = "vm1-monitoring"
machine_type = "e2-medium"
influxdb_vm_ip = "34.60.15.253"
min_replicas = 1
max_replicas = 3
cpu_utilization_target = 0.8
